apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mwdb
  namespace: malwarecage-st
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mwdb
    spec:
      containers:
        - image: "dr.cert.pl/malwarecage/malwarecage_mwdb:latest"
          imagePullPolicy: Always
          name: mwdb-container
          env:
          - name: INJECTS_TOKEN
            valueFrom:
              secretKeyRef:
                name: secret-mwdb-injects-token
                key: token
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secret-mwdb-secret-key
                key: key
          - name: SQLALCHEMY_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: secret-mwdb-database-uri-key
                key: uri
          - name: CUCKOO2_API
            value: http://malwaredb-dev.cert.pl:8090
          - name: INJECTS_URL
            value: https://injects-node.cert.pl/
          - name: MCELERY_URL
            value: http://mcelery-web-service.mcelery-prod.svc.cluster.local/submit
          - name: MWDB_ADMIN_LOGIN
            value: admin
          - name: MWDB_ADMIN_EMAIL
            value: admin@mwdb
          - name: MWDB_ADMIN_PASSWORD
            value: admin
          - name: REDIS_DATABASE_URI
            value: redis://service-mwdb-redis/
          - name: ENABLE_RATE_LIMIT
            value: "1"
          - name: BASE_URL
            value: "https://mwdb-st.cert.pl"
          - name: ENABLE_REGISTRATION
            value: "1"
          - name: MAIL_SMTP
            value: mailhub.cert.pl
          - name: MAIL_FROM
            value: noreply@mwdb-st.cert.pl
          - name: RECAPTCHA_SITE_KEY
            valueFrom:
              secretKeyRef:
                name: secret-mwdb-recaptcha
                key: sitekey
          - name: RECAPTCHA_SECRET
            valueFrom:
              secretKeyRef:
                name: secret-mwdb-recaptcha
                key: secret
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
      nodeSelector:
        kubernetes.io/hostname: k2.cert.pl
---
apiVersion: v1
kind: Service
metadata:
  name: mwdb-service
  namespace: malwarecage-st
spec:
  ports:
     -  name: http
        port: 80
        protocol: TCP
  selector:
    app: mwdb
  type: NodePort
