apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: malwarecage-st
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-mwdb-postgres-password
                key: password
          - name: POSTGRES_DB
            value: mwdb2
          - name: POSTGRES_USER
            value: mwdb
      nodeSelector:
        kubernetes.io/hostname: k2.cert.pl
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: malwarecage-st
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
     protocol: TCP
     targetPort: 5432
  selector:
   app: postgres
